travis:
  secure:
    BINSTAR_TOKEN: ZYBobwqZ/MtkIX4zCuS3fmQ3X5wFB21ezUao/3UL1DO6+llCjALWY8RTpRhohwFgRxAXcHVuRVX9Wiodoy6mDZYo0a6Iqqh68wh2Dv1QQTmxgRPnsjMEj4jhvD+fFuTECczMKKuWMdGnZT/tsWHPj/oVWtB82eYTIgyuY2uFBa7w5ITqG7AOfK/wwebsq8fsVsufwIuxYX2or9Bt03DKplWzFfqVEYqqT+R+6MnnDxEZse4VTCYQGZHVVeqo5FZuzSXQnf7I737Ha8xOEW6OrfjCJAH7FN9ybdH109RdY4xoiOxZ7Ger3uJwoJrnzpgSJaE4AYrdU2d6SjU7TeVsKbqakkAxr13qv2wl6zYhEdFs6R7p0UvkEKmQllDiMDaM0c8FVAu3IYlTkQsYyHIpUc+qa9ZUxf1GHUT5fuhqv+0z856KdfjBKpm5+AFrDiC2JbQkWfBGuTsyjPo0EndfYPagr//pwb5K0t+Qo5PsBgXgi2UHu6kfRmX5xFypWd+vxxReAsLqqKhBRasIKY+WTPcU+LLl+ND5jNXOziSkU3jKkCgKPfvb8dXGRAhwXZ69164BWL6DmWAya5t6LBUXulF900XnD6loumTFHBGnwZpXpwS66Umf7FjNaE2Da052ZIpg468fVXl+JqcwBlKnf44i4+q8zjjiBCXervDKnQY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
