appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: mzOHZ631h/0ijHKeNcLYD1Nyv0qQIN67hNsx0/q1itduhkcwdC0KXmxYOglLEzIUiPjvCKsT+ewm3rj8kgAa4wtKIwGda70ld+Td+yGTex8NxJRz09LRPWA+W8jXNWwBiknnH66w7/g6mYlNMIq+s0c4Pc7H1PuEiaTpzCEqImVxCF2Un4ZDjlDhKgp0sqL3AA/YZYRP4m6HR73OQZkna9Kwaayna68DSaoOTGpXdrbjR5skn5bp0mKZXviOwZaObXb14kclWsCTSKw/UVMFq9/1W97ydm3w39dVHSFrdKRKRqhcrHkDivpgFIqPtVfIdmGjvwZM/UyFuHCvIZRLYK1xgWSzoFb3UeA7x+gbHi1C4HO3mrnQ4QHktzbmUd5X1PAcnh4FK5IAbbaJda/d0H4GjU4eojyFsUJXY7O5ieCwe5Rd/FntNn+PF3if57rSVMPWIQWIfFpk6cfJmyuhEk6ir7zXrlqt7rHJmcwhBtxtOtYJzKPx+JJbw3+dQud0ALZU/HcLj7W6UmsQOOxgt/B9IhGJW0S2PRWOWc8OEPEr0N1fCa4LrcbwIOlXFvxa6Ts20JrTXeiHHcR2N03bvKAt5Y9trs832uv2fWFKkXD08UIgcruNF43zBfhtOjQGmsPcQVWy8SYcQcnTQh2bkCrbW1KJql76L/QR9vilMCU=}
bot:
  automerge: true
